# # JWT (DEV fallback allowed)
# app.jwt.secret=${JWT_SECRET:myDefaultSecretKeyForDevOnly_ChangeInProd}
# app.jwt.expiration=86400000

# Logging (DEV)
logging.level.com.edutech=INFO
logging.level.org.springframework.security=WARN

# H2 Console (DEV only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
